name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Trigger Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
      - uses: actions/checkout@v3
      - run: |
          echo "Inspecting $GITHUB_OUTPUT"
          ls -ld "$GITHUB_TOKEN"
