name: printenv

on:
  workflow_dispatch:

env:
  ENV_SECRET_REPO: ${{ secrets.ENV_SECRET_REPO }}
  ENV_VARIABLE_REPO: ${{ vars.ENV_SECRET_REPO }}

jobs:
  printenv:
    runs-on: ubuntu-latest
    environment: Test
    env:
      ENV_SECRET_TEST: ${{ secrets.ENV_SECRET_TEST }}
      ENV_VARIABLE_TEST: ${{ vars.ENV_VARIABLE_TEST }}
    steps:
      - run: printenv
